# Generated by Django 4.0.5 on 2022-07-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(blank=True, null=True)),
                ('validation', models.BooleanField(default=False)),
                ('product_list', models.ManyToManyField(blank=True, null=True, to='mysite.orderitem')),
            ],
        ),
    ]
