# Generated by Django 4.0.5 on 2022-07-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
