# Generated by Django 4.0.5 on 2022-08-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_orderitem_name_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='client_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
